export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"
export const GETDATA = "GETDATA";


export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP"
export const GOOGLELOGIN = "GOOGLELOGIN";
export const SIGNEDIN = "SIGNEDIN";
export const FORGATEPASSWORD = "FORGATEPASSWORD";
export const LOGOUT = "LOGOUT";
export const LOGGEDIN = "LOGGEDIN";
export const FORGATEDPASSWORD = "FORGATEDPASSWORD";
export const LOGGEDOUT = "LOGGEDOUT";


export const GETCATEGORY = "GETCATEGORY";
export const ADDCATEGORY = "ADDCATEGORY";
export const DELETECATEGORY = "DELETECATEGORY";
export const UPDATECATEGORY = "UPDATECATEGORY";
export const ERRORCATEGORY = "ERRORCATEGORY";

export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"